import { NextResponse } from "next/server";

const urduDict: Record<string, string> = {
  the: "وہ",
  and: "اور",
  is: "ہے",
  are: "ہیں",
  this: "یہ",
  that: "وہ",
  in: "میں",
  on: "پر",
  he: "وہ",
  she: "وہ",
  it: "یہ",
  we: "ہم",
  you: "تم",
  they: "وہ",
  my: "میرا",
  your: "تمہارا",
  good: "اچھا",
  bad: "برا",
  day: "دن",
  night: "رات",
  hello: "سلام",
  world: "دنیا",
  computer: "کمپیوٹر",
  book: "کتاب",
  school: "اسکول",
  student: "طالب علم",
  teacher: "استاد",
  friend: "دوست",
  love: "محبت",
  peace: "امن",
  food: "کھانا",
  water: "پانی",
  house: "گھر",
  car: "گاڑی",
  road: "سڑک",
  city: "شہر",
  country: "ملک",
  language: "زبان",
  english: "انگریزی",
  urdu: "اردو",
  pakistan: "پاکستان",
  india: "بھارت",
  sun: "سورج",
  moon: "چاند",
  star: "ستارہ",
  sky: "آسمان",
  earth: "زمین",
  fire: "آگ",
  air: "ہوا",
  tree: "درخت",
  flower: "پھول",
  happy: "خوش",
  sad: "اداس",
  big: "بڑا",
  small: "چھوٹا",
  fast: "تیز",
  slow: "آہستہ",
  old: "پرانا",
  new: "نیا",
  boy: "لڑکا",
  girl: "لڑکی",
  father: "والد",
  mother: "والدہ",
  brother: "بھائی",
  sister: "بہن",
  child: "بچہ",
  children: "بچے",
  work: "کام",
  play: "کھیلنا",
  run: "دوڑنا",
  walk: "چلنا",
  read: "پڑھنا",
  write: "لکھنا",
  speak: "بولنا",
  listen: "سننا",
  see: "دیکھنا",
  eat: "کھانا",
  drink: "پینا",
  sleep: "سونا",
  wake: "جاگنا",
  open: "کھولنا",
  close: "بند کرنا",
  start: "شروع کرنا",
  end: "ختم کرنا",
  come: "آنا",
  go: "جانا",
  give: "دینا",
  take: "لینا",
  make: "بنانا",
  do: "کرنا",
  know: "جاننا",
  think: "سوچنا",
  understand: "سمجھنا",
  question: "سوال",
  answer: "جواب",
  yes: "ہاں",
  no: "نہیں",
  please: "براہ مہربانی",
  thanks: "شکریہ",
  sorry: "معاف کرنا",
  welcome: "خوش آمدید",
  morning: "صبح",
  evening: "شام",
  today: "آج",
  tomorrow: "کل",
  yesterday: "کل",
  time: "وقت",
  year: "سال",
  month: "مہینہ",
  week: "ہفتہ",
  hour: "گھنٹہ",
  minute: "منٹ",
  second: "سیکنڈ",
  // ...add more as needed
};

export async function POST(request: Request) {
  const { text } = await request.json();
  if (!text || typeof text !== "string") {
    return NextResponse.json({ error: "No text provided" }, { status: 400 });
  }
  const translated = text
    .split(" ")
    .map((word: string) => urduDict[word.toLowerCase()] || word)
    .join(" ");

  return NextResponse.json({ translated });
}
